# Generated by Django 3.2.6 on 2021-08-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tincturas', 'tincturas'), ('cremas', 'cremas'), ('body_lotion', 'body_lotion'), ('gomitas', 'gomitas'), ('vapes', 'vapes')], max_length=20),
        ),
    ]
