# Generated by Django 3.2.6 on 2021-08-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to='products'),
        ),
    ]
