# Generated by Django 3.2.6 on 2021-08-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0003_alter_product_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('affair', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
